### ISSUE TITLE
I've countered some problems..

### ISSUE THREAD

**Issue by muje2002** [AKSHAYUBHAT/VisualSearchServer#13]
Hello, I'm suffering on running your project.
Would you please help me out?

First of all
"--request-payer requester" occurs unkonwn option error.
so I erased it.

but, I get the error like this.
```
[52.201.240.15] Executing task 'demo_nyc'
[localhost] local: aws s3api get-object --bucket aub3visualsearch --key "nyc_index.tar.gz" /mnt/nyc_index.tar.gz
A client error (Unknown) occurred when calling the GetObject operation: Unknown
Fatal error: local() encountered an error (return code 255) while executing 'aws s3api get-object --bucket aub3visualsearch --key "nyc_index.tar.gz" /mnt/nyc_index.tar.gz'
Aborting.
```
so I run cmd directly like this with --debug option.
`aws s3api get-object --debug --bucket aub3visualsearch --key "nyc_index.tar.gz" /mnt/nyc_index.tar.gz`
then, I can check this error. -  **_HTTP Response Code: 403_**
```
2016-05-20 06:47:47,686 - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [GET]>
2016-05-20 06:47:48,303 - botocore.hooks - DEBUG - Event needs-retry.s3.GetObject: calling handler <botocore.retryhandler.RetryHandler object at 0x7f78517a7a20>
2016-05-20 06:47:48,303 - botocore.retryhandler - DEBUG - No retry needed.
2016-05-20 06:47:48,303 - botocore.hooks - DEBUG - Event after-call.s3.GetObject: calling handler <awscli.errorhandler.ErrorHandler object at 0x7f7851b7ce80>
2016-05-20 06:47:48,303 - awscli.errorhandler - DEBUG - **_HTTP Response Code: 403_**
2016-05-20 06:47:48,303 - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/share/awscli/awscli/clidriver.py", line 187, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/share/awscli/awscli/clidriver.py", line 330, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/usr/share/awscli/awscli/clidriver.py", line 438, in __call__
    self._operation_object, call_parameters, parsed_globals)
  File "/usr/share/awscli/awscli/clidriver.py", line 528, in invoke
    **parameters)
  File "/usr/lib/python3/dist-packages/botocore/operation.py", line 82, in call
    parsed=response[1])
  File "/usr/lib/python3/dist-packages/botocore/session.py", line 551, in emit
    return self._events.emit(event_name, **kwargs)
  File "/usr/lib/python3/dist-packages/botocore/hooks.py", line 156, in emit
    response = handler(**kwargs)
  File "/usr/share/awscli/awscli/errorhandler.py", line 75, in __call__
    http_status_code=http_response.status_code)
awscli.errorhandler.ClientError: A client error (Unknown) occurred when calling the GetObject operation: Unknown
2016-05-20 06:47:48,309 - awscli.clidriver - DEBUG - Exiting with rc 255
A client error (Unknown) occurred when calling the GetObject operation: Unknown
```

My AWS instance is in ap-northeeast-1a (Asia Tokyo)
I use IAM user and input the key-id/access-key/region/etc.. by using "aws configure"
and my IAM user or role is in Global (I think it's not associated with specific region)

Do you know any solution about this problem?
then I'll be very appreciated, 

Thanks in advance.

**Comment by AKSHAYUBHAT** [comment]
Hi, 
This is most likely due to the index being store in US standard ("us-east-1")  AWS S3 region. 
Since you are in "ap-northeeast-1a". You can add another argument to following call.

``aws s3api get-object --bucket aub3visualsearch  --region us-east-1 --key "nyc_index.tar.gz" /mnt/nyc_index.tar.gz`
`
By adding following argument 


`--region us-east-1
` 

you can tell AWS to look for the bucket and key in the US standard region, as documented here 
https://blogs.aws.amazon.com/cli/post/TxRGNZ5LAZAYJW/Leveraging-the-s3-and-s3api-Commands

Please tell me if this fixes the problem.

**Comment by muje2002** [comment]
Thank you for your answer, 

I followed your recommend but,  I've still got same error
`aws s3api get-object --debug --bucket aub3visualsearch --region us-east-1 --key "nyc_index.tar.gz" /mnt/nyc_index.tar.gz
`

```
/aub3visualsearch/nyc_index.tar.gz
2016-05-23 07:23:21,441 - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [GET]>
2016-05-23 07:23:22,041 - botocore.hooks - DEBUG - Event needs-retry.s3.GetObject: calling handler <botocore.retryhandler.RetryHandler object at 0x7f884abc3a20>
2016-05-23 07:23:22,041 - botocore.retryhandler - DEBUG - No retry needed.
2016-05-23 07:23:22,041 - botocore.hooks - DEBUG - Event after-call.s3.GetObject: calling handler <awscli.errorhandler.ErrorHandler object at 0x7f884af98e48>
2016-05-23 07:23:22,041 - awscli.errorhandler - DEBUG - HTTP Response Code: 403
2016-05-23 07:23:22,041 - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/share/awscli/awscli/clidriver.py", line 187, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/share/awscli/awscli/clidriver.py", line 330, in __call__
    return command_table[parsed_args.operation](remaining, parsed_globals)
  File "/usr/share/awscli/awscli/clidriver.py", line 438, in __call__
    self._operation_object, call_parameters, parsed_globals)
  File "/usr/share/awscli/awscli/clidriver.py", line 528, in invoke
    **parameters)
  File "/usr/lib/python3/dist-packages/botocore/operation.py", line 82, in call
    parsed=response[1])
  File "/usr/lib/python3/dist-packages/botocore/session.py", line 551, in emit
    return self._events.emit(event_name, **kwargs)
  File "/usr/lib/python3/dist-packages/botocore/hooks.py", line 156, in emit
    response = handler(**kwargs)
  File "/usr/share/awscli/awscli/errorhandler.py", line 75, in __call__
    http_status_code=http_response.status_code)
awscli.errorhandler.ClientError: A client error (Unknown) occurred when calling the GetObject operation: Unknown
2016-05-23 07:23:22,042 - awscli.clidriver - DEBUG - Exiting with rc 255

```

and I set the permission to IAM user in IAM management in AWS console.
but I'm not sure that it is related with above issue..
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:Get*",
                "s3:List*"
            ],
            "Resource": "arn:aws:s3:::aub3visualsearch"
        }
    ]
}
```

Can other people (in not us-east-1) access to your s3 data?

**Comment by AKSHAYUBHAT** [comment]
Can you update awscli, on the instance/ami ? 
Just run following command: 

`
sudo pip install --upgrade awscli
`
I tried from my laptop and the command works.

In the meantime you can download index as well as images for the nyc car dashcam data from following dropbox links:
index: https://www.dropbox.com/s/jc9af66flseepv5/nyc_index.tar.gz?dl=0
images: https://www.dropbox.com/s/6nzuj72e0mj82da/nyc_images.zip?dl=0

Just place index in /mnt/.
To use images you might need to edit few lines in the code.

**Comment by muje2002** [comment]
Very thanks~
