### ISSUE TITLE
HI, I create a instance in the EC, and change the settings.py bucket name of my own, and get those error, In my E2, there exist the /mnt/nyc_index/*.npy

### ISSUE THREAD

**Issue by hasegetc** [AKSHAYUBHAT/VisualSearchServer#9]
> Using index path : /mnt/nyc_index/*.npy
Traceback (most recent call last):
  File "server.py", line 10, in <module>
    from appcode import app
  File "/home/ubuntu/VisualSearchServer/appcode/__init__.py", line 5, in <module>
    import view
  File "/home/ubuntu/VisualSearchServer/appcode/view.py", line 9, in <module>
    index,files = load_index()
  File "/home/ubuntu/VisualSearchServer/inception.py", line 98, in load_index
    index = np.concatenate(index)
ValueError: need at least one array to concatenate

**Comment by AKSHAYUBHAT** [comment]
You can just delete it when indexing with your own data. its trying to create it again, but since it already exists (since you downloaded it) it throws an error.
